filetype: comments

detect:
    filename: "\\.comments$"

rules:
    # Operators
    - comment: "^[ \\t]*(?:#|//|--).*$"
    - info: "^[ \\t]*(?:#|//|--) ?(?:\\w+):.*$"
    - todo: "(?i)^[ \\t]*(?:#|//|--) ?TODO:.*$"
    - error: "(?i)^[ \\t]*(?:#|//|--) ?FIX:.*$"
    - default: "^[\\t ]+"
