filetype: comments

detect:
    filename: "\\.comments$"

rules:
    - todo:
        start: "(?i)^[ \\t]*(?:#|//|--) ?TODO:"
        end: "$"
        rules: []

    - error:
        start: "(?i)^[ \\t]*(?:#|//|--) ?FIX:"
        end: "$"
        rules: []

    - info:
        start: "^[ \\t]*(?:#|//|--) ?(?:\\w+):"
        end: "$"
        rules: []
