filetype: godoc

detect:
    filename: "^package "

rules:
    # Tables (Github extension)
    - normal: ".*\\|.*"
    - md-head:  "^.+:$"
    - function: "func \\w+"
    - function: "\\w+\\(.*?\\)"
    - default: "\\(.*?\\)"
    - function: ", \\w+\\("
    - statement: "\\b(package|import|const|var|type|struct|func|go|defer|iota)\\b"
    - type.keyword: "\\b(u?int(8|16|32|64)?|float(32|64)|complex(64|128))\\b"
    - type.keyword: "\\b(uintptr|byte|rune|string|interface|bool|map|chan|error|struct)\\b"
    - constant.bool: "\\b(true|false|nil)\\b"
    - type.keyword:
        start: "struct {"
        end: "}"
        rules:
            - default: "^\\s+\\w+\\b"
            - comment: " //.+$"
