filetype: javascript

detect:
    filename: "(\\.js$|\\.es[5678]?$|\\.mjs$)"
    header: "^#!.*/(env +)?node( |$)"

rules:
    - constant.number: "\\b[-+]?([1-9][0-9]*|0[0-7]*|0x[0-9a-fA-F]+)([uU][lL]?|[lL][uU]?)?\\b"
    - constant.number: "\\b[-+]?([0-9]+\\.[0-9]*|[0-9]*\\.[0-9]+)([EePp][+-]?[0-9]+)?[fFlL]?"
    - constant.number: "\\b[-+]?([0-9]+[EePp][+-]?[0-9]+)[fFlL]?"
    - identifier: "[A-Za-z_][A-Za-z0-9_\\.]*[[:space:]]?[(\\[]"
    - identifier: "([A-Za-z_][A-Za-z0-9_\\.]+\\.)+"
    - symbol.brackets: "(\\{|\\})"
    - symbol.brackets: "(\\(|\\))"
    - symbol.brackets: "(\\[|\\])"
    - symbol.brackets: "(\\{|\\})"
    - symbol.brackets: "(\\(|\\))"
    - symbol.brackets: "(\\[|\\])"
    - symbol.operator: "[-+/*=<>!~%?:&|]"
    - statement: "\\b(async|await|break|case|catch|const|continue|debugger|default|delete|do|else|export|finally)\\b"
    - statement: "\\b(super|switch|this|throw|try|typeof|var|void|while|with|yield|alert)\\b"
    - error: "\\b(enum|implements|interface|package|private|protected|public)"
    - constant: "\\b(null|undefined|NaN)\\b"
    - constant: "\\b(true|false)\\b"
    - type: "\\b(Array|Boolean|Date|Enumerator|Error|Function|Math)\\b"
    - statement: "\\b(Number|Object|RegExp|String|insert|into|values|update|set|delete|select|from|where|and|or|isnull|join|left|right|outer|as|order by|limit|distinct|on)\\b"
    - constant: "\\\\[0-7][0-7]?[0-7]?|\\\\x[0-9a-fA-F]+|\\\\[bfnrt'\"\\?\\\\]"
    - comment: "^#!.*/(env +)?node( |$)"
    - identifier.var: "([\\$@%]|\\$\\#)\\$*\\{?[a-zA-Z_][a-zA-Z0-9_]*\\}?"
    - comment: "[ \\t;]// .*$"
    - symbol.tag: "</?.+?/?>"
    - symbol.tag: "</?[A-Za-z0-9:]+/?[ >]"
    - special: "&[^;[[:space:]]]*;"
    - constant.tag: "&[\\w]{2,5};"
    - identifier.var: "([\\$@%]|\\$\\#)\\$*[\\p{L}\\p{N}_]*"
    - identifier.var: "\\$+\\{[\\p{L}\\p{N}_]+\\}"
    - symbol: "[:=]"
    - type.keyword1: "\\w+=['\"]"
    - constant.string: "'.*?'"
    - constant.string: "\".*?\""
    - type.keyword: "(alt|bgcolor|(margin)?height|href|id|label|longdesc|name|on(click|focus|load|mouse(over|out)|key(press|up|down)|blur|change|submit|(un)?load)|size|(col|row)?span|src|target|type|value|(margin)?width|cell(spacing|padding)|border|class|method|(enc)?type|maxlength|style|language|action1rel)="
    - constant.number: "(?i)#[0-9A-F]{6,6}"
    - constant.string.url: "(ftp(s)?|http(s)?|git|chrome)://[^ 	]+"
    - comment: "<!--.+?-->"
    - preproc: "<!DOCTYPE.+?>"
    - function: "function \\w+"
    - statement: "\\b(for|function|extends|get|if|import|of|instanceof|let|new|return|set)\\b"
    - identifier.var: "([\\$@%]|\\$\\#)\\$*[a-zA-Z_][a-zA-Z0-9_]*"
    - comment: "^[ \\t]*//.*$"
    - todo: "^[ \\t]*// ?(todo|TODO):.*$"
    - error: "^[ \\t]*// ?(fix|FIX):.*$"
    - default: ";$"

    - constant.string:
        start: "`"
        end: "`"
        rules:
            - constant.specialChar: "\\\\."

    - comment:
        start: "/\\*"
        end: "\\*/"
        rules: []


