filetype: mail

detect:
    filename: "(.*/mutt-.*|\\.eml)$"
    header: "^From .* \\d+:\\d+:\\d+ \\d+"

rules:
    - identifier: "^[^[:space:]]+:"
    - type: "^List-(Id|Archive|Subscribe|Unsubscribe(?:-Post)?|Post|Help):"
    - type: "^X-(?:Campaign\\w+):"
    - type: "^(?:Precedence|Feedback-ID):"
    - statement: "d=.+?;"
    - identifier.var: " \\w{1,2}="
    - md-head: "^(?:To|From|Date|Reply-To):"
    - md-head:
        start: "^Subject:.*"
        end: "$"
        rules:
            - constant.specialChar: "\\\\."
    - statement: "<?[^@[:space:]]+@[^[:space:]]+>?"
    - error: "X-(?:Spam|Ham)-.+?:"
    - constant: "^--.+$"
    - constant: "boundary=.+$"
    - constant:
        start: "^Content-Type: .+?; .+$"
        end: "^--.+$"
        rules:
            - comment: "."
            - constant: "^Content-.+$"
