filetype: markdown

detect:
    filename: "\\.(md|mkd|mkdn|markdown)$"

rules:
    # Tables (Github extension)
    - normal: ".*\\|.*"

    - md-table: "(?:\\|.+?)+\\|"
    - md-bold: "^\\|[^\\|]+"
    - statusline: "\\|"
    # quotes
    - method: "^[:>].+"
    - identifier.var: "^;.+"

      # italic
    - md-italic: "[^_\\w]_(?:.+?)_[^_\\w]"

      # Strong emphasis
    - md-bold: "__(?:.+?)__"
    - md-bold: "\\*\\*(?:.+?)\\*\\*"
    - constant: "`(?:.+?)`"

      # strike-through
    - type: "(^|[[:space:]])~~[^ ][^~]*~~"

      # horizontal rules
    - special: "(---+|===+|___+|\\*\\*\\*+)\\s*$"
    - statusline: "(?:\\|[-:]+)+\\|"

      # headlines
    - md-head:  "^#{1,6}.*"

      # lists
    - identifier:   "^[[:space:]]*[\\*+-] |^[[:space:]]*[0-9]+\\. "

      # misc
    - preproc:   "(\\(([CcRr]|[Tt][Mm])\\)|\\.{3}|(^|[[:space:]])\\-\\-($|[[:space:]]))"

      # links
    - constant: "\\[[^]]+\\]"
    - constant: "\\[([^][]|\\[[^]]*\\])*\\]\\([^)]+\\)"

      # images
    - underlined: "!\\[[^][]*\\](\\([^)]+\\)|\\[[^]]+\\])"

      # urls
    - constant.string.url: "https?://[^ )>]+"

      # mdkdocs,github
    - info: "!!! info .*"
    - info: "> \\[!NOTE\\]"
    - error: "!!! danger .*"
    - error: "> \\[!CAUTION\\]"
    - todo: "!!! warning.*"
    - todo: "> \\[!WARNING\\]"
    - constant.string: "^ {3,}.*"

    # bloques de código
    - label:
        start: "^```perl$"
        end: "^```$"
        rules:
            - default: "."
            - include: "perl"
    - label:
        start: "^```javascript$"
        end: "^```$"
        rules:
            - default: "."
            - include: "javascript"
    - label:
        start: "^```go$"
        end: "^```$"
        rules:
            - default: "."
            - include: "go"
    - label:
        start: "^```lua$"
        end: "^```$"
        rules:
            - default: "."
            - include: "lua"
    - label:
        start: "^```python$"
        end: "^```$"
        rules:
            - default: "."
            - include: "python"
    - label:
        start: "^```html$"
        end: "^```$"
        rules:
            - default: "."
            - include: "html"
            - include: "javascript"
    - label:
        start: "^```(?:\\w+)$"
        end: "^```$"
        rules:
            - comment: "."
    - constant:
        start: "^```$"
        end: "^```$"
        rules:
            - comment: "."

