filetype: markdown

detect:
    filename: "\\.(md|mkd|mkdn|markdown)$"

rules:
    # Tables (Github extension)
    - normal: ".*\\|.*"
    - markup-table: "\\|.*:\\| .*\\|"
    - markup-table: "\\|-+\\|-+\\|"
    - markup-table: "^\\| | \\| ?"

    # quotes
    - statement:  "^>.*"

      # Emphasis
    - method: "(^|[[:space:]])(_[^ ][^_]*_|\\*[^ ][^*]*\\*)"

      # Strong emphasis
    - markup-bold: "(^|[[:space:]])(__[^ ][^_]*__|\\*\\*[^ ][^*]*\\*\\*)"

      # strike-through
    - type: "(^|[[:space:]])~~[^ ][^~]*~~"

      # horizontal rules
    - markup-table: "(---+|===+|___+|\\*\\*\\*+)\\s*$"

      # headlines
    - markup-head:  "^#{1,6}.*"

      # lists
    - identifier:   "^[[:space:]]*[\\*+-] |^[[:space:]]*[0-9]+\\. "

      # misc
    - preproc:   "(\\(([CcRr]|[Tt][Mm])\\)|\\.{3}|(^|[[:space:]])\\-\\-($|[[:space:]]))"

      # links
    - constant: "\\[[^]]+\\]"
    - constant: "\\[([^][]|\\[[^]]*\\])*\\]\\([^)]+\\)"

      # images
    - underlined: "!\\[[^][]*\\](\\([^)]+\\)|\\[[^]]+\\])"

      # urls
    - markup-url: "https?://[^ )>]+"

    - special: "^```$"

    - special: "`.+?`"

