filetype: snippet

detect:
    filename: "\\.snippets?$"

rules:
    - comment: "^[[:space:]]*[#]+.*"
    - constant.string: "\"[^\"\\\\]*(?:\\\\.[^\"\\\\]*)*\""
    - symbol: "\\$\\{\\w+:?.*?\\}"
    - special:
        start: "^snippet"
        end: "$"
        rules:
            - type: "[[:space:]]*\\w+"

