filetype: conf

detect:
    filename: "(passwd|config)$|\\.(c[o]?nf(ig)?|ini|mime|default|cfg)$"
    header: "#[[:space:]]+\\W?\\w{3,}|##+"

rules:
    - constant.number: "[0-9]+(\\.[0-9]+)?([Ee][\\-\\+]?[0-9]+)?"
    # UUIDs
    - constant.number: "[\\w]{8}\\-[\\w]{4}\\-[\\w]{4}\\-[\\w]{4}\\-[\\w]{12}"
    # Domains
    - type.keyword: "((https?|ftp)://)?(\\w+\\.)+(\\w{2,4})?"
    # File paths
    - type.keyword: "\\~?\\/([\\/\\w+\\-\\.\\*])+(\\.\\w+)?"
    # IPS
    - constant.number: "[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}"
    - type.keyword: "yes|none|no|true|false|all|defaults?|swap|ext\\d|auto|password|ask|quiet|verbose"
    - statement: "^[\\w\\-]+[[:space:]]*[\\w\\-]*[:=]"
    - special: "^[\\w\\-]{3,}[[:space:]]+"
    - constant.string: "[[:space:]]*[\\*\\+\\-] \\w+"
    - constant.string: "['\"].*?['\"]"
    - comment: "^[[:space:]]*[#;]+.*"

