filetype: julia

detect:
    filename: "\\.jl$"
    header: "^#!.*/(env +)?julia( |$)"

rules:

    # built-in objects
    - constant.bool: "\\b(true|false)\\b"
      # built-in attributes
    - constant: "__[A-Za-z0-9_]+__"
      # definitions
    - identifier: "[A-Za-z_][A-Za-z0-9_]*[[:space:]]*[(]"
      # keywords
    - statement: "\\b(begin|break|catch|continue|function|elseif|struct|else|end|finally|for|global|local|const|if|include|import|using|require|macro|println|return|try|type|while|module)\\b"
      # decorators
    - identifier.macro: "@[A-Za-z0-9_]+"
      # operators
    - symbol.operator: "[-+*/|=%<>&~^]|\\b(and|not|or|is|in)\\b"
      # parentheses
    - symbol.brackets: "([(){}]|\\[|\\])"
      # numbers
    - constant.number: "\\b[0-9]+\\b"

    - constant.string: "\"(\\\\.|[^\"])*\"|'(\\\\.|[^'])*'"

    - constant.string:
        start: "\"\"\""
        end: "\"\"\""
        rules: []

    - constant.string:
        start: "'''"
        end: "'''"
        rules: []

    - comment:
        start: "#"
        end: "$"
        rules: []
