filetype: text

detect:
    filename: "\\.(text|txt)$"

rules:
    - constant.tag: "^[[:space:]]*[\\*\\-][[:space:]]"
    - constant.tag: "^[[:space:]]*([\\dA-Za-z]+([\\.\\-\\)])+\\w*)+[[:space:]]"
    - constant.string: "\".*?\""
    - constant.string: "'.*?'"
    - statement: "^[[:space:]]*[A-Z ]{3,}"

