#!/usr/bin/perl

use utf8;
binmode STDOUT, 'utf8';

our $FILE = $ARGV[0];

if (!$FILE || !-e $FILE || -d $FILE) {
    exit 1;
}

our $DEBUG = 0;

PrityCode();

exit 0;

sub PrityCode {
    my ($indent, $lc, @quoted_parts, $ci);
    my $L  = 0;
    my $I  = 0;
    my $ch = " ";
    my $sp = 4;

    open(F, "<:utf8", $FILE)       or exit 1;
    open(O, ">:utf8", "$FILE.tmp") or exit 1;
    while (my $l = <F>) {
        $L++;
        if ($DEBUG) {
            print "line: $L\n$l";
        }
        $l =~ s/ +$//;
        $lc = $l;
        $lc =~ s/\n|\r//g;
        if (!$lc || $lc =~ /^\s*#/) {
            print O $l;
            next;
        }
        # Format Text
        # Remove quoted so we do not touch it
        @quoted_parts = safesplit($l);
        for (my $i = 0; $i < scalar(@quoted_parts); $i++) {
            my $q = quotemeta($quoted_parts[$i]);
            if ($DEBUG) {
                print "  quoted string >>> $q\n";
            }
            $l =~ s/$q/XXXXXX$i/g;
        }
        if ($DEBUG) {
            print "  No quotes : $l\n";
        }
        $l =~ s/([\w\"\)])(=|==|>|<|>=|<=|~=|\.\.|\*|\/)([-+\w\"\{])/$1 $2 $3/g;
        $l =~ s/([\d\w\"])(-|\+)([a-zA-Z\W\"])/$1 $2 $3/g;
        $l =~ s/\(\s+\)/\(\)/g;
        $l =~ s/,(\w)/, $1/g;
        $l =~ s/(\()\s+/$1/g;
        $l =~ s/(\S)\s+(\))/$1$2/g;
        for (my $i = 0; $i < scalar(@quoted_parts); $i++) {
            my $q = $quoted_parts[$i];
            $l =~ s/XXXXXX$i/$q/g;
        }
        if ($l !~ /\n$/) {
            $l .= "\n";
        }
        if ($DEBUG) {
            print "  wt quotes : $l";
        }
        # Print formated line
        print O $l;
        if ($DEBUG) {
            print "$l";
            my $x = <STDIN>;
        }
    }
    close O;
    close F;
    if (!$DEBUG) {
        system "mv -f $FILE.tmp $FILE";
    }
}

sub safesplit {
    my $string = shift;
    my @parts  = ();
    my $part   = '';
    my $quote  = 0;

    for (my $i = 0; $i < length($string); $i++) {
        my $c = substr($string, $i, 1);
        if ($quote && $c eq '\\') {
            $i++;
            next;
        }
        if ($quote && $c eq $quote) {
            $part .= $c;
            $quote = 0;
            push @parts, $part;
            $part = "";
        } elsif (!$quote && ($c eq "\"" || $c eq "\'")) {
            $part .= $c;
            $quote = $c;
        } elsif ($quote) {
            $part .= $c;
        }
    }
    return @parts;
}

